services:
  app:
    build: ./server_single
    ports:
      - "8080:8080"
    cpuset: "0"
    cpus: "1.0"
    mem_limit: "256m"
    environment:
      - CSV_LOG_PATH=/app/logs/requests.csv
      - CSV_LOG_APPEND=true
    volumes:
      - ./logs:/app/logs

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports: ["8081:8080"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor

  grafana:
    image: grafana/grafana-oss:latest
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
    - prometheus

volumes:
  grafana-data:
